include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:  
    public_member_api_docs: false
    one_member_abstracts: false
    unnecessary_lambdas: false


    
analyzer:
  language:
    strict-raw-types: true
    strict-casts: false
    strict-inference: false
  exclude:
    - bricks/**
  errors:
    invalid_annotation_target: ignore
