include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:  
    public_member_api_docs: false
    unawaited_futures: false
    lines_longer_than_80_chars: false
    avoid_dynamic_calls: false
    one_member_abstracts: false
    avoid_positional_boolean_parameters: false
    unnecessary_lambdas: false
    prefer_final_locals: false
    use_setters_to_change_properties: false
    use_if_null_to_convert_nulls_to_bools: false

    
analyzer:
  language:
    strict-raw-types: true
    strict-casts: false
    strict-inference: false
  exclude:
    - bricks/**
