name: project_init
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  auto_route: ^7.8.5
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.4
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  dartz: ^0.10.1
  easy_debounce: ^2.0.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.3
  flutter_displaymode: ^0.6.0
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.1.0
  flutter_svg: ^2.0.10+1
  form_validator: ^2.1.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  loading_animation_widget: ^1.2.1
  shared_preferences: ^2.2.2
  upgrader: ^9.0.0
  url_launcher: ^6.2.5

dev_dependencies:
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.4
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: trueœ
  assets:
    - assets/images/
